### ISSUE TITLE
validation of segmentation method

### ISSUE THREAD

**Issue by hz0567** [heyufan1995/self-domain-adapted-network#1]
Hi, thanks for sharing your great work. I have read your MICCAI paper.
The paper said your segmentation  method was validated on two datasets. However, I can only find the source train dataset.  I am wondering  whether the test dataset for your adaptation method is public.

**Comment by YufanHe** [comment]
The repository is updated.
________________________________
From: HongzhengYang ***@***.***>
Sent: Tuesday, June 29, 2021 5:59 AM
To: YufanHe/self-domain-adapted-network ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YufanHe/self-domain-adapted-network] validation of segmentation method (#1)


      External Email - Use Caution



Hi, thanks for sharing your great work. I have read your MICCAI paper.
The paper said your segmentation method was validated on two datasets. However, I can only find the source train dataset. I am wondering whether the test dataset for your adaptation method is public.

**Comment by hz0567** [comment]
Thanks
