### ISSUE TITLE
How to use the code with different data

### ISSUE THREAD

**Issue by gvalvano** [heyufan1995/self-domain-adapted-network#3]
Hello! thanks for sharing this code and congratulation on the paper acceptance at MEDIA!

I would like to reuse your code and try the model on **different datasets**. However, I'm not sure which part of the code I should modify. At [this](https://github.com/YufanHe/self-domain-adapted-network/blob/d7ac918ce306d9f74a845dff2977dc00fbf34563/train.py#L23) line, it seems you are importing a file that is missing from the repo! 

Please, could you help me and point out what are the functions I need to modify to be able to run the code on a different dataset? For example, let's assume I have a dataset under the folder `/path/to/dataset/DATA` and that under it there are images and segmentation masks having names in the list: `[image_0, mask_0, image_1, mask_1, ...., image_N, mask_N]`, and that I have written a function to load images and masks as: `image, mask = load_image_and_mask(image_filename, mask_filename)`.

How could I include this function in your code?

Thanks a lot for any feedback,
G.

**Comment by YufanHe** [comment]
It's in datasets/__init__.py
________________________________
From: Gabriele Valvano ***@***.***>
Sent: Saturday, July 31, 2021 12:37 PM
To: YufanHe/self-domain-adapted-network ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [YufanHe/self-domain-adapted-network] How to use the code with different data (#3)


      External Email - Use Caution



Hello! thanks for sharing this code and congratulation on the paper acceptance at MEDIA!

I would like to reuse your code and try the model on different datasets. However, I'm not sure which part of the code I should modify. At this<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FYufanHe%2Fself-domain-adapted-network%2Fblob%2Fd7ac918ce306d9f74a845dff2977dc00fbf34563%2Ftrain.py%23L23&data=04%7C01%7Cheyufan%40jhu.edu%7C7a5419874a924a36fc3d08d954418495%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637633462652902071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ri8Oqw5iP%2BuxenuKjjc%2BihXYoYlo0pOlI8Mjz91xt6E%3D&reserved=0> line
