### ISSUE TITLE
questions about the reported results 

### ISSUE THREAD

**Issue by nlpLover123** [heyufan1995/self-domain-adapted-network#4]
Hi, thanks for sharing your excellent work. After reading your paper, I am a little confused about the reported performance of the TTT method. It seems that the TTT results are even worse than the non-adaptation baseline.  How did you implement the TTT method? directly input the oct images into the UNet encoder? Cause I find that applying random cropping to the rotation prediction task can improve the performance.

**Comment by YufanHe** [comment]
Hi:
Do you mean the rotation-based method (Rot-NA/Rot)? I described it in the paper
[cid:97b0ccac-7196-4cf5-9dbf-d1dc0fc355f7]
Thanks,
Yufan.
________________________________
From: nlpLover123 ***@***.***>
Sent: Monday, May 16, 2022 11:07 AM
To: heyufan1995/self-domain-adapted-network ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [heyufan1995/self-domain-adapted-network] questions about the reported results (Issue #4)


      External Email - Use Caution



Hi, thanks for sharing your excellent work. After reading your paper, I am a little confused about the reported performance of the TTT method. It seems that the TTT results are even worse than the non-adaptation baseline. How did you implement the TTT method? directly input the oct images into the UNet encoder? Cause I find that applying random cropping to the rotation prediction task can improve the performance.

**Comment by nlpLover123** [comment]
Thanks for your reply. Have you ever tested other self-supervised tasks , such as Flip Prediction or Patch Location Prediction ?
