### ISSUE TITLE
mismatch results of Tent (fully test time adaptation) on OCT segmentation

### ISSUE THREAD

**Issue by ZhengLiu123** [heyufan1995/self-domain-adapted-network#5]
Hi, thanks for sharing your code. I think your idea is very interesting.  However, I have one question related to your MIA paper Table 8.  Indeed, I am trying to reproduce your main results on oct segmentation task. For your method, I can achieve around 82.50% dice score.
But for Tent (fully test time adaptation via entropy minimization), I only achieve 81.23% dice score. And I found that the performance is quite sensitive to the model selection and random seeds. Do you have any comment on this ? Or would you like to share your implementation of Tent on oct segmentation task. Sorry for bothering you.

**Comment by YufanHe** [comment]
I've attached the tent implementation.
Yes, I've found the method indeed sensitive. I think it might be an internal problem of adaptation with only a single test data.
If you read the discussion, we have a whole lot of assumptions about the method, which I think needs improvement.
Thanks,
Yufan.


________________________________
From: ZhengLiu123 ***@***.***>
Sent: Thursday, May 19, 2022 7:53 AM
To: heyufan1995/self-domain-adapted-network ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [heyufan1995/self-domain-adapted-network] mismatch results of Tent (fully test time adaptation) on OCT segmentation (Issue #5)


      External Email - Use Caution



Hi, thanks for sharing your code. I think your idea is very interesting. However, I have one question related to your MIA paper Table 8. Indeed, I am trying to reproduce your main results on oct segmentation task. For your method, I can achieve around 82.50% dice score.
But for Tent (fully test time adaptation via entropy minimization), I only achieve 81.23% dice score. And I found that the performance is quite sensitive to the model selection and random seeds. Do you have any comment on this ? Or would you like to share your implementation of Tent on oct segmentation task. Sorry for bothering you.
